FROM mongo:latest

COPY ./tool/docker-entrypoint.sh /usr/local/bin/
COPY ./tool/initdb.sh /docker-entrypoint-initdb.d/

RUN	chmod +x /usr/local/bin/docker-entrypoint.sh && \
	chmod +x /docker-entrypoint-initdb.d/initdb.sh

ENTRYPOINT [ "docker-entrypoint.sh" ]

#EXPOSE $PORT

CMD [ "mongod" ]