FROM node:21-alpine3.19

LABEL 	name="NestJS" \
		version="1.0" \
		description="NestJS"

#EXPOSE $PORT

ENV HOME /app

WORKDIR $HOME

COPY . .

COPY ./tool/docker-entrypoint.sh /usr/local/bin/

RUN cp ./tool/docker-entrypoint.sh /usr/local/bin/ && \
	cp ./tool/init.sh /usr/local/bin/ && \
	chmod +x /usr/local/bin/docker-entrypoint.sh && \
	chmod +x /usr/local/bin/init.sh

RUN yarn install --frozen-lockfile && yarn build

ENTRYPOINT [ "docker-entrypoint.sh" ]

CMD [ "init.sh" ]